CREATE TABLE IF NOT EXISTS assets (
    asset_tag VARCHAR(255) PRIMARY KEY,
    payload JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS institutions (
    name VARCHAR(255) PRIMARY KEY,
    sites JSONB NOT NULL DEFAULT '[]',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);