# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import rental_pb2 as rental__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rental_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RentalServiceStub:
    """============================================================================
    RENTAL SERVICE
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddProperty = channel.unary_unary(
                '/rental.RentalService/AddProperty',
                request_serializer=rental__pb2.AddPropertyRequest.SerializeToString,
                response_deserializer=rental__pb2.AddPropertyResponse.FromString,
                _registered_method=True)
        self.UpdateProperty = channel.unary_unary(
                '/rental.RentalService/UpdateProperty',
                request_serializer=rental__pb2.UpdatePropertyRequest.SerializeToString,
                response_deserializer=rental__pb2.UpdatePropertyResponse.FromString,
                _registered_method=True)
        self.RemoveProperty = channel.unary_unary(
                '/rental.RentalService/RemoveProperty',
                request_serializer=rental__pb2.RemovePropertyRequest.SerializeToString,
                response_deserializer=rental__pb2.RemovePropertyResponse.FromString,
                _registered_method=True)
        self.SearchProperty = channel.unary_unary(
                '/rental.RentalService/SearchProperty',
                request_serializer=rental__pb2.SearchPropertyRequest.SerializeToString,
                response_deserializer=rental__pb2.SearchPropertyResponse.FromString,
                _registered_method=True)
        self.BookProperty = channel.unary_unary(
                '/rental.RentalService/BookProperty',
                request_serializer=rental__pb2.BookPropertyRequest.SerializeToString,
                response_deserializer=rental__pb2.BookPropertyResponse.FromString,
                _registered_method=True)
        self.ConfirmBooking = channel.unary_unary(
                '/rental.RentalService/ConfirmBooking',
                request_serializer=rental__pb2.ConfirmBookingRequest.SerializeToString,
                response_deserializer=rental__pb2.ConfirmBookingResponse.FromString,
                _registered_method=True)
        self.SearchUser = channel.unary_unary(
                '/rental.RentalService/SearchUser',
                request_serializer=rental__pb2.SearchUserRequest.SerializeToString,
                response_deserializer=rental__pb2.SearchUserResponse.FromString,
                _registered_method=True)
        self.SearchBooking = channel.unary_unary(
                '/rental.RentalService/SearchBooking',
                request_serializer=rental__pb2.SearchBookingRequest.SerializeToString,
                response_deserializer=rental__pb2.SearchBookingResponse.FromString,
                _registered_method=True)
        self.RemoveBooking = channel.unary_unary(
                '/rental.RentalService/RemoveBooking',
                request_serializer=rental__pb2.RemoveBookingRequest.SerializeToString,
                response_deserializer=rental__pb2.RemoveBookingResponse.FromString,
                _registered_method=True)
        self.CreateUsers = channel.stream_unary(
                '/rental.RentalService/CreateUsers',
                request_serializer=rental__pb2.User.SerializeToString,
                response_deserializer=rental__pb2.CreateUsersResponse.FromString,
                _registered_method=True)
        self.ListAvailableProperties = channel.unary_stream(
                '/rental.RentalService/ListAvailableProperties',
                request_serializer=rental__pb2.ListAvailableRequest.SerializeToString,
                response_deserializer=rental__pb2.Property.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_stream(
                '/rental.RentalService/ListUsers',
                request_serializer=rental__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=rental__pb2.User.FromString,
                _registered_method=True)
        self.ListBookings = channel.unary_stream(
                '/rental.RentalService/ListBookings',
                request_serializer=rental__pb2.ListBookingsRequest.SerializeToString,
                response_deserializer=rental__pb2.Booking.FromString,
                _registered_method=True)
        self.ListRemovedBookings = channel.unary_stream(
                '/rental.RentalService/ListRemovedBookings',
                request_serializer=rental__pb2.ListRemovedBookingsRequest.SerializeToString,
                response_deserializer=rental__pb2.RemovedBooking.FromString,
                _registered_method=True)


class RentalServiceServicer:
    """============================================================================
    RENTAL SERVICE
    ============================================================================

    """

    def AddProperty(self, request, context):
        """========================================================================
        SIMPLE RPCs
        ========================================================================

        ------------------------------------------------------------------------
        Property management
        ------------------------------------------------------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BookProperty(self, request, context):
        """------------------------------------------------------------------------
        Cart / booking
        ------------------------------------------------------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchUser(self, request, context):
        """------------------------------------------------------------------------
        User lookup
        ------------------------------------------------------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchBooking(self, request, context):
        """------------------------------------------------------------------------
        Booking lookup / removal
        ------------------------------------------------------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUsers(self, request_iterator, context):
        """========================================================================
        CLIENT-SIDE STREAMING
        ========================================================================

        Client sends many User messages.

        Server returns one CreateUsersResponse after the client completes
        the stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAvailableProperties(self, request, context):
        """========================================================================
        SERVER-SIDE STREAMING
        ========================================================================

        ------------------------------------------------------------------------
        Available properties
        ------------------------------------------------------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """------------------------------------------------------------------------
        All users / hosts / guests
        ------------------------------------------------------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBookings(self, request, context):
        """------------------------------------------------------------------------
        Active bookings
        ------------------------------------------------------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRemovedBookings(self, request, context):
        """------------------------------------------------------------------------
        Removed booking history
        ------------------------------------------------------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RentalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProperty,
                    request_deserializer=rental__pb2.AddPropertyRequest.FromString,
                    response_serializer=rental__pb2.AddPropertyResponse.SerializeToString,
            ),
            'UpdateProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProperty,
                    request_deserializer=rental__pb2.UpdatePropertyRequest.FromString,
                    response_serializer=rental__pb2.UpdatePropertyResponse.SerializeToString,
            ),
            'RemoveProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveProperty,
                    request_deserializer=rental__pb2.RemovePropertyRequest.FromString,
                    response_serializer=rental__pb2.RemovePropertyResponse.SerializeToString,
            ),
            'SearchProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchProperty,
                    request_deserializer=rental__pb2.SearchPropertyRequest.FromString,
                    response_serializer=rental__pb2.SearchPropertyResponse.SerializeToString,
            ),
            'BookProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.BookProperty,
                    request_deserializer=rental__pb2.BookPropertyRequest.FromString,
                    response_serializer=rental__pb2.BookPropertyResponse.SerializeToString,
            ),
            'ConfirmBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmBooking,
                    request_deserializer=rental__pb2.ConfirmBookingRequest.FromString,
                    response_serializer=rental__pb2.ConfirmBookingResponse.SerializeToString,
            ),
            'SearchUser': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchUser,
                    request_deserializer=rental__pb2.SearchUserRequest.FromString,
                    response_serializer=rental__pb2.SearchUserResponse.SerializeToString,
            ),
            'SearchBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchBooking,
                    request_deserializer=rental__pb2.SearchBookingRequest.FromString,
                    response_serializer=rental__pb2.SearchBookingResponse.SerializeToString,
            ),
            'RemoveBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveBooking,
                    request_deserializer=rental__pb2.RemoveBookingRequest.FromString,
                    response_serializer=rental__pb2.RemoveBookingResponse.SerializeToString,
            ),
            'CreateUsers': grpc.stream_unary_rpc_method_handler(
                    servicer.CreateUsers,
                    request_deserializer=rental__pb2.User.FromString,
                    response_serializer=rental__pb2.CreateUsersResponse.SerializeToString,
            ),
            'ListAvailableProperties': grpc.unary_stream_rpc_method_handler(
                    servicer.ListAvailableProperties,
                    request_deserializer=rental__pb2.ListAvailableRequest.FromString,
                    response_serializer=rental__pb2.Property.SerializeToString,
            ),
            'ListUsers': grpc.unary_stream_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=rental__pb2.ListUsersRequest.FromString,
                    response_serializer=rental__pb2.User.SerializeToString,
            ),
            'ListBookings': grpc.unary_stream_rpc_method_handler(
                    servicer.ListBookings,
                    request_deserializer=rental__pb2.ListBookingsRequest.FromString,
                    response_serializer=rental__pb2.Booking.SerializeToString,
            ),
            'ListRemovedBookings': grpc.unary_stream_rpc_method_handler(
                    servicer.ListRemovedBookings,
                    request_deserializer=rental__pb2.ListRemovedBookingsRequest.FromString,
                    response_serializer=rental__pb2.RemovedBooking.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rental.RentalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rental.RentalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RentalService:
    """============================================================================
    RENTAL SERVICE
    ============================================================================

    """

    @staticmethod
    def AddProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.RentalService/AddProperty',
            rental__pb2.AddPropertyRequest.SerializeToString,
            rental__pb2.AddPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.RentalService/UpdateProperty',
            rental__pb2.UpdatePropertyRequest.SerializeToString,
            rental__pb2.UpdatePropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.RentalService/RemoveProperty',
            rental__pb2.RemovePropertyRequest.SerializeToString,
            rental__pb2.RemovePropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.RentalService/SearchProperty',
            rental__pb2.SearchPropertyRequest.SerializeToString,
            rental__pb2.SearchPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BookProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.RentalService/BookProperty',
            rental__pb2.BookPropertyRequest.SerializeToString,
            rental__pb2.BookPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.RentalService/ConfirmBooking',
            rental__pb2.ConfirmBookingRequest.SerializeToString,
            rental__pb2.ConfirmBookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.RentalService/SearchUser',
            rental__pb2.SearchUserRequest.SerializeToString,
            rental__pb2.SearchUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.RentalService/SearchBooking',
            rental__pb2.SearchBookingRequest.SerializeToString,
            rental__pb2.SearchBookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.RentalService/RemoveBooking',
            rental__pb2.RemoveBookingRequest.SerializeToString,
            rental__pb2.RemoveBookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUsers(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/rental.RentalService/CreateUsers',
            rental__pb2.User.SerializeToString,
            rental__pb2.CreateUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAvailableProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rental.RentalService/ListAvailableProperties',
            rental__pb2.ListAvailableRequest.SerializeToString,
            rental__pb2.Property.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rental.RentalService/ListUsers',
            rental__pb2.ListUsersRequest.SerializeToString,
            rental__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rental.RentalService/ListBookings',
            rental__pb2.ListBookingsRequest.SerializeToString,
            rental__pb2.Booking.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRemovedBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rental.RentalService/ListRemovedBookings',
            rental__pb2.ListRemovedBookingsRequest.SerializeToString,
            rental__pb2.RemovedBooking.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
